SELECT 
	BOARD_TYPE, 	-- 게시글 타입
	BOARD_NUM,		-- 게시글 번호
	BOARD_TITLE,	-- 게시글 제목
	BOARD_COMMENT,	-- 게시글 내용
	CREATOR,		-- 생성자
	CREATE_TIME,	-- 생성시간
	MODIFIER,		-- 수정자
	MODIFIED_TIME,	-- 수정시간
	FILE_ROOT		-- 파일
FROM BOARD
ORDER BY BOARD_TYPE, BOARD_NUM DESC;



INSERT INTO BOARD(BOARD_TYPE, BOARD_NUM, BOARD_TITLE, BOARD_COMMENT, CREATOR, CREATE_TIME, MODIFIER, MODIFIED_TIME, FILE_ROOT) 
VALUES('1', 1, '테스트', '테스트 합니다.01', 'SYSTEM', TO_CHAR(SYSDATE), 'SYSTEM', TO_CHAR(SYSDATE), '파일')


SELECT BOARD_TYPE
	,BOARD_NUM
	,BOARD_TITLE
	,BOARD_COMMENT
FROM BOARD
WHERE BOARD_TYPE = '1'
AND BOARD_NUM  = 5


INSERT INTO BOARD (BOARD_TYPE ,BOARD_NUM ,BOARD_TITLE ,BOARD_COMMENT ,CREATOR ,CREATE_TIME, MODIFIER ,MODIFIED_TIME)
VALUES (
		 (	SELECT CODE_ID FROM COM_CODE
			WHERE CODE_NAME = '일반')
        ,(	SELECT NVL(MAX(BOARD_NUM)+1, 1)
			FROM BOARD
			WHERE BOARD_TYPE = (SELECT CODE_ID FROM COM_CODE WHERE CODE_NAME = '일반'))
        ,'테스트 제목'
        ,'테스트 내용'
        ,'SYSTEM'
        ,TO_CHAR(SYSDATE)
        ,'SYSTEM'
        ,TO_CHAR(SYSDATE)
        )
        
INSERT INTO BOARD (BOARD_TYPE ,BOARD_NUM ,BOARD_TITLE ,BOARD_COMMENT ,CREATOR ,CREATE_TIME, MODIFIER ,MODIFIED_TIME)
VALUES (
		 'a01'
        ,(	SELECT NVL(MAX(BOARD_NUM)+1, 1)
			FROM BOARD
			WHERE BOARD_TYPE = 'a01')
        ,'테스트 제목'
        ,'테스트 내용'
        ,'SYSTEM'
        ,TO_CHAR(SYSDATE)
        ,'SYSTEM'
        ,TO_CHAR(SYSDATE)
        )
        
        
INSERT INTO BOARD(BOARD_TYPE ,BOARD_NUM ,BOARD_TITLE ,BOARD_COMMENT ,CREATOR ,CREATE_TIME, MODIFIER ,MODIFIED_TIME)
VALUES (
		 'a1'
        , 1
        ,'테스트'
        ,'테스트내용'
        ,'SYSTEM'
        ,TO_CHAR(SYSDATE)
        ,'SYSTEM'
        ,TO_CHAR(SYSDATE)
        )        
        

UPDATE BOARD
SET BOARD_TITLE = 'ㅇㅇㅇ', BOARD_COMMENT = '수정수정'
WHERE BOARD_TYPE = '1'
AND BOARD_NUM = 5

DELETE FROM BOARD
WHERE BOARD_TYPE = 'a01'
AND BOARD_NUM = 2


SELECT NVL(MAX(BOARD_NUM)+1, 1)
FROM BOARD
WHERE BOARD_TYPE = '1'


SELECT 
	  BOARD_TYPE
	  ,BOARD_NUM
	  ,BOARD_TITLE
	  ,BOARD_COMMENT
	  ,TOTAL_CNT
FROM (
	  SELECT
	      	BOARD_TYPE
			,BOARD_NUM
			,BOARD_TITLE
			,BOARD_COMMENT
	      	,ROW_NUMBER() OVER(ORDER BY BOARD_NUM DESC) AS NUMROW
	      	,COUNT(*) OVER() AS TOTAL_CNT
		FROM BOARD	
		WHERE BOARD_TYPE IN ('a01', 'a02', 'a03', 'a04') -- trim 이용
	 )
WHERE NUMROW BETWEEN (1-1)*10 + 1 AND (1)*10


--===========================================================================

SELECT 
	CODE_TYPE,
	CODE_ID,
	CODE_NAME,
	CREATOR,
	CREATE_TIME
	MODIFIER,
	MODIFIED_TIME
FROM COM_CODE;

SELECT CODE_ID FROM COM_CODE
WHERE CODE_NAME = 'Q&A' 


SELECT CODE_ID, CODE_NAME 
FROM COM_CODE
WHERE CODE_TYPE = 'phone'
		

--===========================================================================

SELECT 
	USER_ID,		-- pk, 15byte 
	USER_PW,		-- 16byte, 
	USER_NAME,		-- 이름
	USER_PHONE1,	-- 010
	USER_PHONE2,	-- 앞자리 '1234'
	USER_PHONE3,	-- 뒷자리 '5678'
	USER_ADDR1,		-- postNo : 우편번호 ex) 'xxx-xxx'
	USER_ADDR2,		-- 나머지 주소  
	USER_COMPANY,	-- 회사명
	CREATOR,		-- 'SYSTEM'
	CREATE_TIME,    -- TO_CHAR(SYSDATE)
	MODIFIER,		-- 'SYSTEM'
	MODIFIED_TIME	-- TO_CHAR(SYSDATE)
FROM USER_INFO

SELECT COUNT(*) FROM USER_INFO
WHERE USER_ID = 'testUser01'

SELECT * FROM USER_INFO
WHERE USER_ID = 'test01'
AND USER_PW = 'a12345'

INSERT INTO 
USER_INFO(
	USER_ID
	,USER_PW
	,USER_NAME
	,USER_PHONE1
	,USER_PHONE2
	,USER_PHONE3
	,USER_ADDR1
	,USER_ADDR2
	,USER_COMPANY
	,CREATOR
	,CREATE_TIME
	,MODIFIER
	,MODIFIED_TIME
	)
	VALUES(
		'testUser01'
		,'a1234'
		,'홍길동'
		,'010'
		,'xxxx'
		,'xxxx'
		,'123-345'
		,'서울시 구로구 디지털로 242 한화비즈메트로 1차'
		,'넥스트아이씨티'
		,'SYSTEM'
        ,TO_CHAR(SYSDATE)
        ,'SYSTEM'
        ,TO_CHAR(SYSDATE)
        )        
		
DELETE FROM USER_INFO 
WHERE USER_ID = 'testUser01'
        
        
        
        
        
        
        
        
        
        



